# Copyright (C) 2019 The MoKee Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/dragon/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/acr_ucode.bin:ramdisk/vendor/firmware/nouveau/acr_ucode.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/fecs.bin:ramdisk/vendor/firmware/nouveau/fecs.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/fecs_sig.bin:ramdisk/vendor/firmware/nouveau/fecs_sig.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/gpmu_ucode_desc.bin:ramdisk/vendor/firmware/nouveau/gpmu_ucode_desc.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/gpmu_ucode_image.bin:ramdisk/vendor/firmware/nouveau/gpmu_ucode_image.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_bundle:ramdisk/vendor/firmware/nouveau/nv12b_bundle \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_fuc409c:ramdisk/vendor/firmware/nouveau/nv12b_fuc409c \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_fuc409d:ramdisk/vendor/firmware/nouveau/nv12b_fuc409d \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_fuc41ac:ramdisk/vendor/firmware/nouveau/nv12b_fuc41ac \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_fuc41ad:ramdisk/vendor/firmware/nouveau/nv12b_fuc41ad \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_method:ramdisk/vendor/firmware/nouveau/nv12b_method \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_sw_ctx:ramdisk/vendor/firmware/nouveau/nv12b_sw_ctx \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/nv12b_sw_nonctx:ramdisk/vendor/firmware/nouveau/nv12b_sw_nonctx \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/pmu_bl.bin:ramdisk/vendor/firmware/nouveau/pmu_bl.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nouveau/pmu_sig.bin:ramdisk/vendor/firmware/nouveau/pmu_sig.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nvidia/tegra210/bpmp.bin:ramdisk/vendor/firmware/nvidia/tegra210/bpmp.bin \
    vendor/google/dragon/proprietary/vendor/firmware/nvidia/tegra210/xusb.bin:ramdisk/vendor/firmware/nvidia/tegra210/xusb.bin
